<?php
$env    = isset($_SERVER['_ENV']) && $_SERVER['_ENV'] == "production" ? 'prod' : 'dev';
$less   = array('bootstrap', 'mixins', 'style', 'pageDesigns', 'quickview', 'loading');
?><html lang=en xmlns=http://www.w3.org/1999/xhtml>
<head>
    <title>Ruin It For Me
    </title>
    <meta http-equiv=Content-Type content="text/html; charset=utf-8"/>
    <meta http-equiv=Content-Type content=cache/>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
    <meta name="description" content="Description">
    <meta name="revisit-after" content="30 days">
    <meta name="distribution" content="web">
    <meta name="keywords" content="keywords">

    <!--Fonts-->
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,700,300' rel='stylesheet' type='text/css'>
    <!-- compiled less file -->
    <?php foreach ($less as $file) { ?>
        <?php if ($env == "prod") { ?>
    <link rel="stylesheet" type="text/css" href="/css/<?php echo $file; ?>.css" />
    <?php } else { ?>
    <link rel="stylesheet/less" type="text/css" href="/css/<?php echo $file; ?>.less" />
    <?php } ?>
        <script src="/js/libs/less.js" type="text/javascript"></script>
    <?php } ?>

    <!-- library design -->
    <link media="screen" rel="stylesheet" type="text/css" href="/js/libs/jquery/jquery-ui-1.10.3.custom.min.css" />
</head>
<body>
<div id="quickviewLatch"></div>
<div id="wrapper">
    <div id="sidebar">
        <div id="sidebarInner">
            <div class="area">
                <h3>Spoilers</h3>
                <ul>
                    <li>
                        <span class="circle red"></span>
                        <a href="#newest">Newest</a>
                    </li>
                    <li>
                        <span class="circle green"></span>
                        <a href="#mostViewed">Most Viewed</a>
                    </li>
                    <li>
                        <span class="circle yellow"></span>
                        <a href="#trending">Trending</a>
                    </li>
                </ul>
            </div>
            <div class="area">
                <h3>Other</h3>
                <ul>
                    <li>
                        <span class="circle purple"></span>
                        <a href="#createSpoiler">Create Spoiler</a>
                    </li>
                    <li>
                        <span class="circle blue"></span>
                        <a href="#contactUs">Contact Us</a>
                    </li>
                </ul>
            </div>
            <br />
        </div>
    </div>
    <div id="content">
        <div id="contentInner"></div>
    </div>
</div>
<script data-main="js/main" src="js/libs/require/require.js"></script>
</body>
</html>